"""empty message

Revision ID: 1126b153ac52
Revises: 1a1d393d981f
Create Date: 2024-08-29 00:08:46.826602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1126b153ac52'
down_revision = '1a1d393d981f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('spotify_id', sa.String(length=64), nullable=False),
    sa.Column('apple_music_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('playlist_table', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playlist_table_apple_music_id'), ['apple_music_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_playlist_table_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_playlist_table_spotify_id'), ['spotify_id'], unique=False)

    op.create_table('user_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=265), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_table_username'), ['username'], unique=True)

    op.create_table('userplaylist_table',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist_table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'playlist_id')
    )
    with op.batch_alter_table('playlist', schema=None) as batch_op:
        batch_op.drop_index('ix_playlist_apple_music_id')
        batch_op.drop_index('ix_playlist_name')
        batch_op.drop_index('ix_playlist_spotify_id')

    op.drop_table('playlist')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_username')

    op.drop_table('user')
    with op.batch_alter_table('user_playlist', schema=None) as batch_op:
        batch_op.drop_index('ix_user_playlist_playlist_id')
        batch_op.drop_index('ix_user_playlist_user_id')

    op.drop_table('user_playlist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_playlist',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('playlist_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_playlist', schema=None) as batch_op:
        batch_op.create_index('ix_user_playlist_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_user_playlist_playlist_id', ['playlist_id'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=265), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_username', ['username'], unique=1)

    op.create_table('playlist',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('spotify_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('apple_music_id', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('playlist', schema=None) as batch_op:
        batch_op.create_index('ix_playlist_spotify_id', ['spotify_id'], unique=False)
        batch_op.create_index('ix_playlist_name', ['name'], unique=False)
        batch_op.create_index('ix_playlist_apple_music_id', ['apple_music_id'], unique=False)

    op.drop_table('userplaylist_table')
    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_table_username'))

    op.drop_table('user_table')
    with op.batch_alter_table('playlist_table', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playlist_table_spotify_id'))
        batch_op.drop_index(batch_op.f('ix_playlist_table_name'))
        batch_op.drop_index(batch_op.f('ix_playlist_table_apple_music_id'))

    op.drop_table('playlist_table')
    # ### end Alembic commands ###
