"""empty message

Revision ID: 1a1d393d981f
Revises: dde482f6bd5b
Create Date: 2024-08-28 22:53:30.557113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a1d393d981f'
down_revision = 'dde482f6bd5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('spotify_id', sa.String(length=64), nullable=False),
    sa.Column('apple_music_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('playlist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playlist_apple_music_id'), ['apple_music_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_playlist_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_playlist_spotify_id'), ['spotify_id'], unique=False)

    op.create_table('user_playlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_playlist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_playlist_playlist_id'), ['playlist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_playlist_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_playlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_playlist_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_playlist_playlist_id'))

    op.drop_table('user_playlist')
    with op.batch_alter_table('playlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playlist_spotify_id'))
        batch_op.drop_index(batch_op.f('ix_playlist_name'))
        batch_op.drop_index(batch_op.f('ix_playlist_apple_music_id'))

    op.drop_table('playlist')
    # ### end Alembic commands ###
