"""empty message

Revision ID: 8c260276458f
Revises: 
Create Date: 2024-08-29 21:55:31.721230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c260276458f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('spotify_id', sa.String(length=64), nullable=False),
    sa.Column('apple_music_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('playlist_table', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playlist_table_apple_music_id'), ['apple_music_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_playlist_table_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_playlist_table_spotify_id'), ['spotify_id'], unique=False)

    op.create_table('user_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_table_username'), ['username'], unique=True)

    op.create_table('userplaylist_table',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist_table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'playlist_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userplaylist_table')
    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_table_username'))

    op.drop_table('user_table')
    with op.batch_alter_table('playlist_table', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playlist_table_spotify_id'))
        batch_op.drop_index(batch_op.f('ix_playlist_table_name'))
        batch_op.drop_index(batch_op.f('ix_playlist_table_apple_music_id'))

    op.drop_table('playlist_table')
    # ### end Alembic commands ###
