"""empty message

Revision ID: b0325e1aeb8b
Revises: 8c260276458f
Create Date: 2024-08-30 13:24:26.662280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0325e1aeb8b'
down_revision = '8c260276458f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist_table', schema=None) as batch_op:
        batch_op.drop_index('ix_playlist_table_apple_music_id')
        batch_op.drop_index('ix_playlist_table_spotify_id')
        batch_op.drop_column('spotify_id')
        batch_op.drop_column('apple_music_id')

    with op.batch_alter_table('userplaylist_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform_id', sa.String(length=64), nullable=False))
        batch_op.create_index(batch_op.f('ix_userplaylist_table_platform_id'), ['platform_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userplaylist_table', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_userplaylist_table_platform_id'))
        batch_op.drop_column('platform_id')

    with op.batch_alter_table('playlist_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apple_music_id', sa.VARCHAR(length=64), nullable=False))
        batch_op.add_column(sa.Column('spotify_id', sa.VARCHAR(length=64), nullable=False))
        batch_op.create_index('ix_playlist_table_spotify_id', ['spotify_id'], unique=False)
        batch_op.create_index('ix_playlist_table_apple_music_id', ['apple_music_id'], unique=False)

    # ### end Alembic commands ###
